export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";

export const FETCH_FAILURE = "FETCH_FAILURE";

export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';